# Generated by Django 5.2.5 on 2025-10-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
    ]
